# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/GNNcoalV2',
                'doc_host': 'https://kevinkorfmann.github.io',
                'git_url': 'https://github.com/kevinkorfmann/GNNcoalV2',
                'lib_path': 'GNNcoalV2'},
  'syms': {'GNNcoalV2.core': {'GNNcoalV2.core.foo': ('core.html#foo', 'GNNcoalV2/core.py')}}}
